### ISSUE TITLE
https://hanzi.cri-paris.org/#S3

### ISSUE THREAD

**Issue by captainflunch** [hugolpz/OpenEdx-hanzi#19]
Bonjour,
sous Firefox, je ne peux accéder au site en cliquant sur le lien donné dans le MOOC. Les infos que me donne Firefox sont : connexion non sécurisée, des éléments de la page, tels que images, ne sont pas sécurisés.
![hanzi](https://user-images.githubusercontent.com/24205434/36517257-eb4c656c-1781-11e8-91f7-d391e38e30a3.PNG)
![hanzi1](https://user-images.githubusercontent.com/24205434/36517258-eb8d2bba-1781-11e8-87b7-7c34e4034a8c.PNG)

**Comment by hugolpz** [comment]
Bonjour Captain,

(1) Est-ce que ceci est bloquant et pop up avant que tu accède à la page web ? = problème important 

(2) Ou est-ce que tu inspectes volontairement des certificats de notre site ? = problème léger

**Comment by hugolpz** [comment]
I think we solved this issue.
See: #20.

**Comment by captainflunch** [comment]
Don't think so : once more i could not get access.

**Comment by hugolpz** [comment]
Hello Captain ! Please could do the following in this order :
1) Do you know how to inspect the code of the page ? Could you share the console, there may be some alerts ? Screenshot or copy paste will do.
2) Clean the webpage's cache. I'am currently beta-testing micro-monitoring, and I may have done something wrong.

**Comment by hugolpz** [comment]
I added some code to clean your cache.
May work.
Please join screenshot so i get some clue. :)
